### ISSUE TITLE
redux-persist@^5.0.0 compatibility

### ISSUE THREAD

**Issue by bartlomn** [edy/redux-persist-transform-filter#15]
Things seem to be working, npm complains about peer dependencies though.
Please advise.

**Comment by edy** [comment]
i haven't tested redux-persist-transform-filter for compatibility with redux-persist v5 yet.

if it works for you, it's fine. if not, stay with v4 until i update. otherwise: patches are welcome

**Comment by edy** [comment]
the tests are passing with redux-persist 5.0.1, so i think you can ignore the warning and i'll release a new version soon

**Comment by rt2zz** [comment]
right there were no explicit breaking changes to the transforms api so this should work as expected. It is *possible* there could be some weird interactions with new usage patterns that v5 enables though, e.g. nesting persists.

**Comment by edy** [comment]
i released 0.0.16 on npm

**Comment by bartlomn** [comment]
Thank you good Sir! Much obliged 👍
