### ISSUE TITLE
redux-persist@^6.x.x compatibility

### ISSUE THREAD

**Issue by thclark** [edy/redux-persist-transform-filter#27]
Sorry to be the messenger. Yup, javascript dependency hell strikes again, and redux-persist has increased by a mazor version, which means users of this library get:
```
npm WARN redux-persist-transform-filter@0.0.18 requires a peer of redux-persist@^3.4.0 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
```

The good news is it looks like this doesn't affect you, since there are [no breaking changes to the api except initialising redux-persist for react native.](https://github.com/rt2zz/redux-persist/releases)... so likely just a case of bumping the version compatibility.

**Comment by edy** [comment]
Thank for noticing. I just released 0.0.19
