### ISSUE TITLE
Lodash function imports cause errors

### ISSUE THREAD

**Issue by AregShahbazian** [edy/redux-persist-transform-filter#39]
I'm using `"redux-persist-transform-filter": "^0.0.21",` and getting these 4 errors:

`ERROR in ./node_modules/redux-persist-transform-filter/dist/index.js 28:14-38`
`Module not found: Error: Can't resolve 'lodash/pickby'`

`ERROR in ./node_modules/redux-persist-transform-filter/dist/index.js 32:15-40`
`Module not found: Error: Can't resolve 'lodash/isempty'`

`ERROR in ./node_modules/redux-persist-transform-filter/dist/index.js 36:13-36`
`Module not found: Error: Can't resolve 'lodash/forin'`

`ERROR in ./node_modules/redux-persist-transform-filter/dist/index.js 40:17-44`
`Module not found: Error: Can't resolve 'lodash/clonedeep' `

Looking at the code it looks like these [four import statements](https://github.com/edy/redux-persist-transform-filter/blob/48252316cfce459f9da53a9416d31d9ca137f17d/index.js#L5) should use camelcase, like:
`import pickBy from 'lodash/pickBy'` instead of
`import pickBy from 'lodash/pickby'`, etc...

**Comment by meftunca** [comment]
Same issue

**Comment by edy** [comment]
fixed in 0.0.22

**Comment by AregShahbazian** [comment]
Thank you!
